org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)

neo_version=21.1.230
neo_version_range=[21,)
loader_version_range=[4,)

parchment_minecraft_version = same
parchment_version = 2024.11.17

mod_id=async_opac_compat
mod_name=Async OPAC Compat
mod_license=MIT
mod_version=0.1.0
mod_group_id=dev.tuxebro
mod_authors=TuxeBro
mod_description=Make Async and OPAC get along I guess. (aka. fix explosion greifing)
